import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from '@/components/providers';
import "./globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'
// import Navbar from "@/components/navbar/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Account &ndash; Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Providers>
        {/* <Navbar /> */}
        <ToastContainer />
        {children}
        <div id="modal-root"></div>
      </Providers>
      </body>
    </html>
  );
}
